substitutions:
  friendly_name: Zehnder ComfoAir Q
  device_name: zehnder-comfoair-q
  device_description: Zehnder ComfoAir Q HRV (heat recovery ventilation) unit
  filter_time: 5s
  filter_send_every: "1"
  filter_window_size: "3"

packages:
  remote_package:
    url: https://github.com/SkullboyNL/esphome-zehnder-comfoair
    refresh: 0s
    files: [ 
      boards/esp32-wifi.yml,
      packages/binary_sensors.yml,
      packages/board.yml,
      packages/button.yml,
      packages/canbus.yml,
      packages/climate.yml,
      packages/common.yml,
      packages/fan.yml,
      packages/select.yml,
      packages/sensors.yml,
      packages/switch.yml,
      packages/text_sensors.yml,
    ]

dashboard_import:
  package_import_url: github://SkullboyNL/esphome-zehnder-comfoair/zehnder-comfoair-q-wifi-v1.yml
  import_full_config: false # or true

  
external_components:
  - components: [ zehnder_comfoair_q ]
    # uncomment for local dev
    # source: components
    source: github://SkullboyNL/esphome-zehnder-comfoair@main
    
esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: yoziru.esphome-zehnder-comfoair
    version: "2024.8.0"

logger:
  level: INFO
  logs:
    canbus: INFO

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_rrm: true
  enable_btm: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:


captive_portal:
improv_serial:

web_server:
  port: 80

    
# See docs: https://github.com/michaelarnauts/aiocomfoconnect/blob/master/docs/PROTOCOL-PDO.md
zehnder_comfoair_q:
  id: comfoair
  request_ids:
    [
      16,
      49,
      54,
      55,
      65,
      66,
      67,
      81,
      82,
      117,
      118,
      119,
      120,
      121,
      122,
      128,
      129,
      130,
      192,
      209,
      210,
      211,
      212,
      212,
      213,
      214,
      215,
      216,
      217,
      218,
      220,
      221,
      225,
      227,
      274,
      275,
      276,
      277,
      278,
      290,
      291,
      292,
      293,
      294,
    ]
