substitutions:
  can_tx_pin: GPIO20
  can_rx_pin: GPIO21
  board: esp32-c3-devkitm-1
  variant: esp32c3
  flash_size: 4MB
 

light:
  - platform: status_led
    name: "Status LED"
    id: led
    icon: "mdi:alarm-light"
    restore_mode: ALWAYS_OFF
    pin:
      number: GPIO8
      inverted: false